### PR TITLE
Expose the CPU profiler on the V8Runtime

### PR DESCRIPTION
**Pull request by erik-kallen**
This PR makes it possible to use the V8 CPU profiler with ClearScript. The StopCpuProfiler method returns a string that can be saved to a file and then imported into Chrome DevTools.

It has been a while since I last wrote any C++, but it seems to work.

### CODE REVIEW

**Comment by ClearScriptLib** [comment]
Hi @erik-kallen,

Your change appears to serialize the profile into a JSON string.

1. How does one use this string?
1. Is the JSON schema documented somewhere?
1. Would it make sense to expose the profile as a data structure instead?

Thanks again!

**Comment by erik-kallen** [comment]
1. You save it to a file and open it in Chrome DevTools (chrome://inspect -> Open dedicated DevTools for Node -> Profiler -> Load
2. Not very well-documented, but I found some docs at https://chromium.googlesource.com/v8/v8/+/master/src/inspector/js_protocol.json
3. Maybe (I probably will actually end up parsing the returned structure myself in my project), but we would run into the problem that we either need to create the managed structures inside the V8IsolateImpl class, which seems to go agains the architecture, or in some other way guarantee that we don't run into problems when the returned profile is used after `END_ISOLATE_SCOPE`.

**Comment by erik-kallen** [comment]
Sorry, forgot to mention you, @ClearScriptLib

**Comment by ClearScriptLib** [comment]
Hi @erik-kallen,

Thanks for contributing and responding. We feel it would be better, API-wise, to expose the full profile model similarly to the way V8 exposes it, along with a JSON serialization method for DevTools import. We'll be taking a closer look at this in the near future.

Thanks again!

**Comment by erik-kallen** [comment]
Thank you for considering this, it would be really helpful for us to have it.

If you give me some directions, I can try do do some of the work (but as I said, my C++ is quite rusty).

**Comment by erik-kallen** [comment]
Any news on this?

Anything I can do to make it happen faster?

**Comment by ClearScriptLib** [comment]
Hi @erik-kallen,

We've begun the work on a full profiling API, but there's no ETA. Sorry! ClearScript is a side project, so major enhancements can take a while.

Thanks!

**Comment by erik-kallen** [comment]
As I said before, with some directions, I would be happy to help

**Comment by ClearScriptLib** [comment]
[Version 5.5.6](https://github.com/Microsoft/ClearScript/releases/tag/5.5.6) includes new APIs for V8 CPU profiling.

Thanks again for your ideas and contribution!

**Comment by erik-kallen** [comment]
Thank you! Can't wait to try (although it might take a while before I have the means of doing it)

**Comment by erik-kallen** [comment]
Just want to say that the profiler in 5.5.6 works like a charm! Thank you!

**Pull request closed without merging**
