### PR TITLE
Async error handling

### PR DESCRIPTION
**Pull request by Ellested**
I needed the ToTask and ToPromise extensions to work well with error handling in most of the normal uses cases. So tried to mimic these in LinqPad, where I fixed some issues in the current implementation. It blocked the thread when exceptions was thrown. 

It was a small change, but it happened to be really hard to share it with a PR, as nothing worked out of the box on my machine.

### So a little story on that:
It might be a good idea to put some effort into the V8 build, as I almost gave up (and it's such a shame if it stops any people from contributing). My VS installation also needed a repair before it recognized the .net framework unit test project type - to be fair.

I was told that you are looking into shipping a pre-built V8 engine, which I think would remove all the hassle of getting started - should probably be a priority.

Anyway, the first two commits has only to do with getting the project up and running (and pass all tests). After cleaning up all my system/user paths to a bare minimum, and substituting the build path with a drive letter, it completed the 32 bit V8 build, but still failed on the 64 bit. I was told that some people have had success with setlocal/endlocal, so I added this - and it finally completed both builds. 

But it was to much of a struggle finding out the reasons, as you don't get clear and informative errors back (nature of batch commands) - you need to dig it out. But thanks for all the help I received, from the ClearScript maintainer(s). 

Depending on your VS installation, your Developer Command prompt might have a variable number of paths configured (it will add its own locations. to your system/user defined paths), The V8build.cmd is very dependent (fragile) on the total length of the paths, and if you see "line too long" errors, it's likely due to a path concatenation statement failing somewhere. I've also seen some "mysterious" Python errors (code 255), when it tries to read out the env variables, and I guess it's also caused by the same issue, as they went away with the other efforts.

**NB:** I tried to run all test using a C# language version 7.3 compilation (including my original code). It works exactly the same, so I don't see why you should stay on the old version, unless you have some other tooling that need's it.

I can submit a PR if you like - now that everything is finally running :-)

### CODE REVIEW

**Comment by ClearScriptLib** [comment]
Hi @Ellested,

Thanks for your contribution!

As you've noticed, our original [`ToPromise`](https://microsoft.github.io/ClearScript/Reference/html/Overload_Microsoft_ClearScript_JavaScript_JavaScriptExtensions_ToPromise.htm) implementation was utterly broken with respect to error handling. We merged an [earlier PR](https://github.com/microsoft/ClearScript/pull/184) to fix that.

We're currently testing the next ClearScript release, which further refines error handling and adds `ToTask` as we discussed. One issue with the current implementation is that it doesn't comply with our preferred exception scheme, which places restrictions on the kinds of exceptions we throw ([`Error`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error)-based objects within JavaScript, [`ScriptEngineException`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_ScriptEngineException.htm) outside). Our changes in this area are likely to conflict with your PR, but we'll take another look after the release.

Sorry about the V8Update issues. The V8 build relies on a large, rapidly changing custom toolchain and has always been problematic; Windows doesn't appear to be the V8 team's primary platform. Admittedly it has gotten _more_ problematic lately, so we'll take a look at that too.

Thanks again!

**Comment by Ellested** [comment]
OK, got it :-)

I just needed to make sure that it worked for my purposes, before starting to actually try and implement it (which I'm doing at the moment).

The PR fix didn't work alone, at least not in LinqPad where I started to fiddle with the error handling. In ToTask I had to undo the lambda declarations, and use the delegates instead - otherwise it just blocked. Might be LinqPad related, but might also be something you need to consider.

I think you should just include the V8 binaries in the repo (with .pdb files), then the V8Update.cmd is not a critical part anymore.

Final request - please attach any CLR exceptions to your custom JS Error object, as abstracting the origin away would be a shame.

Looking forward to see what you come up with, and cool that you are lifting the C#5 constraint - it will make your life easier ;-)

**Comment by ClearScriptLib** [comment]
Hi @Ellested,

> In ToTask I had to undo the lambda declarations, and use the delegates instead - otherwise it just blocked. Might be LinqPad related, but might also be something you need to consider.

Would you mind posting details on how to reproduce this issue?

>I think you should just include the V8 binaries in the repo (with .pdb files), then the V8Update.cmd is not a critical part anymore.

We post a NuGet package, including the V8 binaries, on the day of each release. Unfortunately NuGet's symbol support doesn't work for ClearScript, so we're looking for another solution. The other issue is the V8 header files, which we'd prefer not to include in the ClearScript repository.

> Final request - please attach any CLR exceptions to your custom JS Error object, as abstracting the origin away would be a shame.

ClearScript preserves the exception chain across the host-script boundary. Script exceptions that originated in managed code have a `hostException` property, and there's [`ScriptException`](https://microsoft.github.io/ClearScript/Reference/html/P_Microsoft_ClearScript_ScriptEngineException_ScriptException.htm) for the reverse. Our new `ToPromise`/`ToTask` implementation complies with this pattern.

Cheers!

**Comment by Ellested** [comment]
[ClearScript ToTask Blocking.zip](https://github.com/microsoft/ClearScript/files/4659425/ClearScript.ToTask.Blocking.zip)

It's a LinqPad6 file, and note that LinqPad does not work with the ClearScript Nuget package out of the box. But as far as I recall, it will tell you in which folder it cannot find the V8 dll's, so it's just a manual copy to get it running. I haven't tried to make a unit test in ClearScript to reproduce it, as I started all my ground testing in LinqPad, and soon discovered that ToTask blocked (and I just changed it into something like ToTask2).

**Comment by ClearScriptLib** [comment]
@Ellested,

Thank you very much for posting the LINQPad file. It helped us validate our new `ToTask` implementation.

Note that, in your test, the only difference between `ToTask` and `ToTask2` is the method used to get the error string - `toString` vs. `ToString`. Each can fail depending on what kind of object is passed to `onRejected`. In this case it's a .NET exception, which has no `toString` method, so `onRejected` throws before it can call `SetException` to complete the task.

Cheers!

**Comment by Ellested** [comment]
Ofc, I didn't notice that. I just took your original, unwrapped the lambda's to be able to set a breakpoint in LinqPad. But it didn't block from there on, so I just noticed that I had an issue with the original, not that I accidentally made it work with ToString :-)

**Comment by ClearScriptLib** [comment]
This issue was fixed in [Version 6.0.2](https://github.com/microsoft/ClearScript/releases/tag/6.0.2).

**Pull request closed without merging**
